export const HOUSE_BUFFER_RADIUS = 1;
export const BUILDABLE_SLOPE_LIMIT = 0.07;
export const FRONTAGE_SCAN_MARGIN = 8;
export const TOWN_CORE_RADIUS = 3;
export const MIN_TOWN_RADIUS = 4;
export const COASTAL_PROFILE_WATER_DISTANCE_MAX = 4;
export const RIBBON_TOWN_WATER_DISTANCE_MAX = 2;
export const RIBBON_TOWN_RELIEF_MIN = 0.022;
export const RIBBON_TOWN_MIN_BUILD_SPAN = 4;
export const BASE_PRE_GROWTH_YEARS = 20;
export const MAX_SETTLEMENT_PRE_GROWTH_YEARS = 40;
export const FRONTIER_EXTENSION_MIN = 2;
export const FRONTIER_EXTENSION_MAX = 5;
export const SECONDARY_BRANCH_MIN = 2;
export const SECONDARY_BRANCH_MAX = 4;
export const COMPACT_TOWN_BLOCK_OFFSET = 4;
export const COMPACT_TOWN_CONNECTOR_OFFSET = 2;
export const COMPACT_TOWN_INTERIOR_BRANCH_SCAN_RADIUS = 2;
export const COMPACT_TOWN_MIN_CORE_HOUSES = 8;
export const COMPACT_TOWN_ASPECT_SOFT_LIMIT = 2.15;
export const COMPACT_TOWN_ASPECT_HARD_LIMIT = 2.85;
export const COMPACT_TOWN_LONG_AXIS_PENALTY = 2.2;
export const COMPACT_TOWN_MAX_ROAD_RADIUS = 8;
export const COMPACT_TOWN_BRANCH_TARGET_ROAD_BUFFER = 1;
export const TOWN_INITIAL_BUILD_COOLDOWN_MAX_DAYS = 18;
export const TOWN_BUILD_START_COOLDOWN_MIN_DAYS = 4;
export const TOWN_BUILD_START_COOLDOWN_MAX_DAYS = 9;
export const TOWN_CONSTRUCTION_SLOWDOWN_FACTOR = 0.5;
export const TOWN_CONSTRUCTION_SLOW_POSTURE = 2;
export const TOWN_CONSTRUCTION_PAUSE_POSTURE = 3;
export const BUILDING_EMPTY_LOT_DURATION_DAYS = 3;
export const BUILDING_SITE_PREP_DURATION_DAYS = 4;
export const BUILDING_FRAME_DURATION_DAYS = 7;
export const BUILDING_ENCLOSED_DURATION_DAYS = 6;
export const BUILDING_CLEARED_LOT_DURATION_DAYS = 5;
export const BUILDING_RUIN_PERSISTENCE_DAYS = 18;
export const MAX_FRONTIERS_BY_ARCHETYPE = {
  ribbon: 3,
  main_street: 4,
  crossroads: 4,
  contour: 4
} as const;
